version: '3'
services:
  node:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/src
      - node-modules:/src/node_modules
    working_dir: /src
    tty: true
    command: npm run dev
volumes:
  node-modules: