name: deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branchs:
      - main

jobs:
  deploy:
    # Name the Job
    name: deploy
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Site
        run:
          docker-compose run node npm install
          docker-compose run --rm node npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_KEY }}
        with:
          publish-dir: ./app/dist
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
